export const GET_DATA = 'GET_DATA'
export const GET_DATA_ID = 'GET_DATA_ID'
export const POST_DATA_ID = 'POST_DATA_ID'
export const PUT_DATA_ID = 'PUT_DATA_ID'
export const DEL_DATA_ID = 'DEL_DATA_ID'
